// source: sensr_proto/output.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_api_annotations_pb = require('../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var argos_proto_type_pb = require('../argos_proto/type_pb.js');
goog.object.extend(proto, argos_proto_type_pb);
var sensr_proto_type_pb = require('../sensr_proto/type_pb.js');
goog.object.extend(proto, sensr_proto_type_pb);
goog.exportSymbol('proto.sensr_proto.Command', null, global);
goog.exportSymbol('proto.sensr_proto.CommandRequest', null, global);
goog.exportSymbol('proto.sensr_proto.CommandResponse', null, global);
goog.exportSymbol('proto.sensr_proto.OutputMessage', null, global);
goog.exportSymbol('proto.sensr_proto.RegularObjectResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensr_proto.CommandRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensr_proto.CommandRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensr_proto.CommandRequest.displayName = 'proto.sensr_proto.CommandRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensr_proto.CommandResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sensr_proto.CommandResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensr_proto.CommandResponse.displayName = 'proto.sensr_proto.CommandResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensr_proto.RegularObjectResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sensr_proto.RegularObjectResponse.repeatedFields_, null);
};
goog.inherits(proto.sensr_proto.RegularObjectResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensr_proto.RegularObjectResponse.displayName = 'proto.sensr_proto.RegularObjectResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sensr_proto.OutputMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sensr_proto.OutputMessage.repeatedFields_, null);
};
goog.inherits(proto.sensr_proto.OutputMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sensr_proto.OutputMessage.displayName = 'proto.sensr_proto.OutputMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensr_proto.CommandRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.sensr_proto.CommandRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensr_proto.CommandRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.CommandRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    command: jspb.Message.getFieldWithDefault(msg, 1, 0),
    paramMap: (f = msg.getParamMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensr_proto.CommandRequest}
 */
proto.sensr_proto.CommandRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensr_proto.CommandRequest;
  return proto.sensr_proto.CommandRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensr_proto.CommandRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensr_proto.CommandRequest}
 */
proto.sensr_proto.CommandRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sensr_proto.Command} */ (reader.readEnum());
      msg.setCommand(value);
      break;
    case 2:
      var value = msg.getParamMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensr_proto.CommandRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensr_proto.CommandRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensr_proto.CommandRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.CommandRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommand();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getParamMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional Command command = 1;
 * @return {!proto.sensr_proto.Command}
 */
proto.sensr_proto.CommandRequest.prototype.getCommand = function() {
  return /** @type {!proto.sensr_proto.Command} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sensr_proto.Command} value
 * @return {!proto.sensr_proto.CommandRequest} returns this
 */
proto.sensr_proto.CommandRequest.prototype.setCommand = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * map<string, string> param = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.sensr_proto.CommandRequest.prototype.getParamMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.sensr_proto.CommandRequest} returns this
 */
proto.sensr_proto.CommandRequest.prototype.clearParamMap = function() {
  this.getParamMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensr_proto.CommandResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.sensr_proto.CommandResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensr_proto.CommandResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.CommandResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    returnCode: jspb.Message.getFieldWithDefault(msg, 1, 0),
    paramMap: (f = msg.getParamMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensr_proto.CommandResponse}
 */
proto.sensr_proto.CommandResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensr_proto.CommandResponse;
  return proto.sensr_proto.CommandResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensr_proto.CommandResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensr_proto.CommandResponse}
 */
proto.sensr_proto.CommandResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReturnCode(value);
      break;
    case 2:
      var value = msg.getParamMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensr_proto.CommandResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensr_proto.CommandResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensr_proto.CommandResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.CommandResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReturnCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getParamMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional int32 return_code = 1;
 * @return {number}
 */
proto.sensr_proto.CommandResponse.prototype.getReturnCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sensr_proto.CommandResponse} returns this
 */
proto.sensr_proto.CommandResponse.prototype.setReturnCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * map<string, string> param = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.sensr_proto.CommandResponse.prototype.getParamMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.sensr_proto.CommandResponse} returns this
 */
proto.sensr_proto.CommandResponse.prototype.clearParamMap = function() {
  this.getParamMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sensr_proto.RegularObjectResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensr_proto.RegularObjectResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.sensr_proto.RegularObjectResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensr_proto.RegularObjectResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.RegularObjectResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeStamp: (f = msg.getTimeStamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    objectsList: jspb.Message.toObjectList(msg.getObjectsList(),
    sensr_proto_type_pb.Object.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensr_proto.RegularObjectResponse}
 */
proto.sensr_proto.RegularObjectResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensr_proto.RegularObjectResponse;
  return proto.sensr_proto.RegularObjectResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensr_proto.RegularObjectResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensr_proto.RegularObjectResponse}
 */
proto.sensr_proto.RegularObjectResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeStamp(value);
      break;
    case 2:
      var value = new sensr_proto_type_pb.Object;
      reader.readMessage(value,sensr_proto_type_pb.Object.deserializeBinaryFromReader);
      msg.addObjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensr_proto.RegularObjectResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensr_proto.RegularObjectResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensr_proto.RegularObjectResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.RegularObjectResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeStamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getObjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      sensr_proto_type_pb.Object.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp time_stamp = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.sensr_proto.RegularObjectResponse.prototype.getTimeStamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.sensr_proto.RegularObjectResponse} returns this
*/
proto.sensr_proto.RegularObjectResponse.prototype.setTimeStamp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensr_proto.RegularObjectResponse} returns this
 */
proto.sensr_proto.RegularObjectResponse.prototype.clearTimeStamp = function() {
  return this.setTimeStamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensr_proto.RegularObjectResponse.prototype.hasTimeStamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Object objects = 2;
 * @return {!Array<!proto.sensr_proto.Object>}
 */
proto.sensr_proto.RegularObjectResponse.prototype.getObjectsList = function() {
  return /** @type{!Array<!proto.sensr_proto.Object>} */ (
    jspb.Message.getRepeatedWrapperField(this, sensr_proto_type_pb.Object, 2));
};


/**
 * @param {!Array<!proto.sensr_proto.Object>} value
 * @return {!proto.sensr_proto.RegularObjectResponse} returns this
*/
proto.sensr_proto.RegularObjectResponse.prototype.setObjectsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sensr_proto.Object=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sensr_proto.Object}
 */
proto.sensr_proto.RegularObjectResponse.prototype.addObjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sensr_proto.Object, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensr_proto.RegularObjectResponse} returns this
 */
proto.sensr_proto.RegularObjectResponse.prototype.clearObjectsList = function() {
  return this.setObjectsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sensr_proto.OutputMessage.repeatedFields_ = [2,101];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sensr_proto.OutputMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.sensr_proto.OutputMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sensr_proto.OutputMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.OutputMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    timeStamp: (f = msg.getTimeStamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    objectsList: jspb.Message.toObjectList(msg.getObjectsList(),
    argos_proto_type_pb.Object.toObject, includeInstance),
    regionOfInterestList: jspb.Message.toObjectList(msg.getRegionOfInterestList(),
    argos_proto_type_pb.Zone.toObject, includeInstance),
    groundPoints: msg.getGroundPoints_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sensr_proto.OutputMessage}
 */
proto.sensr_proto.OutputMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sensr_proto.OutputMessage;
  return proto.sensr_proto.OutputMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sensr_proto.OutputMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sensr_proto.OutputMessage}
 */
proto.sensr_proto.OutputMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeStamp(value);
      break;
    case 2:
      var value = new argos_proto_type_pb.Object;
      reader.readMessage(value,argos_proto_type_pb.Object.deserializeBinaryFromReader);
      msg.addObjects(value);
      break;
    case 101:
      var value = new argos_proto_type_pb.Zone;
      reader.readMessage(value,argos_proto_type_pb.Zone.deserializeBinaryFromReader);
      msg.addRegionOfInterest(value);
      break;
    case 102:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setGroundPoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sensr_proto.OutputMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sensr_proto.OutputMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sensr_proto.OutputMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sensr_proto.OutputMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimeStamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getObjectsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      argos_proto_type_pb.Object.serializeBinaryToWriter
    );
  }
  f = message.getRegionOfInterestList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      101,
      f,
      argos_proto_type_pb.Zone.serializeBinaryToWriter
    );
  }
  f = message.getGroundPoints_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      102,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp time_stamp = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.sensr_proto.OutputMessage.prototype.getTimeStamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.sensr_proto.OutputMessage} returns this
*/
proto.sensr_proto.OutputMessage.prototype.setTimeStamp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sensr_proto.OutputMessage} returns this
 */
proto.sensr_proto.OutputMessage.prototype.clearTimeStamp = function() {
  return this.setTimeStamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sensr_proto.OutputMessage.prototype.hasTimeStamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated argos_proto.Object objects = 2;
 * @return {!Array<!proto.argos_proto.Object>}
 */
proto.sensr_proto.OutputMessage.prototype.getObjectsList = function() {
  return /** @type{!Array<!proto.argos_proto.Object>} */ (
    jspb.Message.getRepeatedWrapperField(this, argos_proto_type_pb.Object, 2));
};


/**
 * @param {!Array<!proto.argos_proto.Object>} value
 * @return {!proto.sensr_proto.OutputMessage} returns this
*/
proto.sensr_proto.OutputMessage.prototype.setObjectsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.argos_proto.Object=} opt_value
 * @param {number=} opt_index
 * @return {!proto.argos_proto.Object}
 */
proto.sensr_proto.OutputMessage.prototype.addObjects = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.argos_proto.Object, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensr_proto.OutputMessage} returns this
 */
proto.sensr_proto.OutputMessage.prototype.clearObjectsList = function() {
  return this.setObjectsList([]);
};


/**
 * repeated argos_proto.Zone region_of_interest = 101;
 * @return {!Array<!proto.argos_proto.Zone>}
 */
proto.sensr_proto.OutputMessage.prototype.getRegionOfInterestList = function() {
  return /** @type{!Array<!proto.argos_proto.Zone>} */ (
    jspb.Message.getRepeatedWrapperField(this, argos_proto_type_pb.Zone, 101));
};


/**
 * @param {!Array<!proto.argos_proto.Zone>} value
 * @return {!proto.sensr_proto.OutputMessage} returns this
*/
proto.sensr_proto.OutputMessage.prototype.setRegionOfInterestList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 101, value);
};


/**
 * @param {!proto.argos_proto.Zone=} opt_value
 * @param {number=} opt_index
 * @return {!proto.argos_proto.Zone}
 */
proto.sensr_proto.OutputMessage.prototype.addRegionOfInterest = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 101, opt_value, proto.argos_proto.Zone, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sensr_proto.OutputMessage} returns this
 */
proto.sensr_proto.OutputMessage.prototype.clearRegionOfInterestList = function() {
  return this.setRegionOfInterestList([]);
};


/**
 * optional bytes ground_points = 102;
 * @return {!(string|Uint8Array)}
 */
proto.sensr_proto.OutputMessage.prototype.getGroundPoints = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 102, ""));
};


/**
 * optional bytes ground_points = 102;
 * This is a type-conversion wrapper around `getGroundPoints()`
 * @return {string}
 */
proto.sensr_proto.OutputMessage.prototype.getGroundPoints_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getGroundPoints()));
};


/**
 * optional bytes ground_points = 102;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getGroundPoints()`
 * @return {!Uint8Array}
 */
proto.sensr_proto.OutputMessage.prototype.getGroundPoints_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getGroundPoints()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.sensr_proto.OutputMessage} returns this
 */
proto.sensr_proto.OutputMessage.prototype.setGroundPoints = function(value) {
  return jspb.Message.setProto3BytesField(this, 102, value);
};


/**
 * @enum {number}
 */
proto.sensr_proto.Command = {
  CMD_NONE: 0,
  CMD_START: 1,
  CMD_STOP: 2,
  CMD_STOP_PROG: 3,
  CMD_LOAD: 4,
  CMD_SAVE: 5,
  CMD_SELECT_ITEM: 6,
  CMD_DESELECT_ITEM: 7,
  CMD_CUSTOM: 8
};

goog.object.extend(exports, proto.sensr_proto);
